// <auto-generated />
using System;
using FEMEE.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FEMEE.Infrastructure.Migrations
{
    [DbContext(typeof(FemeeDbContext))]
    partial class FemeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FEMEE.Domain.Entities.Campeonatos.Campeonato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("CIDADE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_FIM");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_INICIO");

                    b.Property<DateTime>("DataLimiteInscricao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_LIMITE_INSCRICAO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("ESTADO");

                    b.Property<int>("FaseCampeonato")
                        .HasColumnType("int")
                        .HasColumnName("FASE_CAMPEONATO");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("BANNER_CAMPEONATO_URL");

                    b.Property<int>("JogoId")
                        .HasColumnType("int");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("LOCAL");

                    b.Property<int>("NumeroInscritos")
                        .HasColumnType("int")
                        .HasColumnName("NUMERO_INSCRITOS");

                    b.Property<int>("NumeroVagas")
                        .HasColumnType("int")
                        .HasColumnName("NUMERO_VAGAS");

                    b.Property<decimal>("Premiacao")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PREMIACAO");

                    b.Property<string>("RegulamentoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("REGULAMENTO_URL");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS_CAMPEONATO");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("TITULO");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("JogoId")
                        .HasDatabaseName("IX_CAMPEONATO_JOGOID");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_CAMPEONATO_STATUS");

                    b.ToTable("T_CAMPEONATO", (string)null);
                });

            modelBuilder.Entity("FEMEE.Domain.Entities.Campeonatos.InscricaoCampeonato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampeonatoId")
                        .HasColumnType("int")
                        .HasColumnName("CAMPEONATO_ID");

                    b.Property<int?>("CapitaoId")
                        .HasColumnType("int")
                        .HasColumnName("CAPITAO_ID");

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_INSCRICAO");

                    b.Property<string>("EmailContato")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL_CONTATO");

                    b.Property<string>("NomeCapitao")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NOME_CAPITAO");

                    b.Property<string>("NomeTime")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NOME_TIME");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("OBSERVACOES");

                    b.Property<int>("StatusInscricao")
                        .HasColumnType("int")
                        .HasColumnName("STATUS_INSCRICAO");

                    b.Property<string>("TelefoneContato")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TELEFONE_CONTATO");

                    b.Property<int?>("TimeId")
                        .HasColumnType("int")
                        .HasColumnName("TIME_ID");

                    b.HasKey("Id");

                    b.HasIndex("CapitaoId");

                    b.HasIndex("StatusInscricao")
                        .HasDatabaseName("IX_INSCRICAO_CAMPEONATO_STATUS");

                    b.HasIndex("TimeId");

                    b.HasIndex("CampeonatoId", "TimeId")
                        .IsUnique()
                        .HasDatabaseName("IX_INSCRICAOCAMPEONATO_CAMPEONATOID_TIMEID_UNIQUE")
                        .HasFilter("[TIME_ID] IS NOT NULL");

                    b.ToTable("T_INSCRICAO_CAMPEONATOS", (string)null);
                });

            modelBuilder.Entity("FEMEE.Domain.Entities.Campeonatos.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ATIVO");

                    b.Property<int>("CategoriaJogo")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_JOGO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("IMAGEM_URL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NOME");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("SLUG");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_JOGO_SLUG_UNIQUE");

                    b.ToTable("T_JOGOS", (string)null);
                });

            modelBuilder.Entity("FEMEE.Domain.Entities.Campeonatos.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampeonatoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_HORA");

                    b.Property<int>("Fase")
                        .HasColumnType("int")
                        .HasColumnName("FASE");

                    b.Property<string>("Local")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("LOCAL");

                    b.Property<int>("PlacarTimeA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("PLACAR_TIME_A");

                    b.Property<int>("PlacarTimeB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("PLACAR_TIME_B");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS_PARTIDA");

                    b.Property<int>("TimeAId")
                        .HasColumnType("int")
                        .HasColumnName("TIME_A_ID");

                    b.Property<int>("TimeBId")
                        .HasColumnType("int")
                        .HasColumnName("TIME_B_ID");

                    b.Property<int?>("TimeVencedorId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("TIME_VENCEDOR_ID");

                    b.Property<string>("TransmissaoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("TRANSMISSAO_URL");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId")
                        .HasDatabaseName("IX_PARTIDA_CAMPEONATOID");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PARTIDA_STATUS");

                    b.HasIndex("TimeAId");

                    b.HasIndex("TimeBId");

                    b.HasIndex("TimeVencedorId");

                    b.HasIndex("CampeonatoId", "DataHora")
                        .HasDatabaseName("IX_PARTIDA_CAMPEONATOID_DATAHORA");

                    b.ToTable("T_PARTIDAS", (string)null);
                });

            modelBuilder.Entity("FEMEE.Domain.Entities.Campeonatos.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DataFundacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_FUNDACAO");

                    b.Property<int>("Derrotas")
                        .HasColumnType("int")
                        .HasColumnName("DERROTAS");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int>("Empates")
                        .HasColumnType("int")
                        .HasColumnName("EMPATES");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("LOGO_URL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("TIME_NOME");

                    b.Property<int>("Pontos")
                        .HasColumnType("int")
                        .HasColumnName("PONTOS");

                    b.Property<int>("PosicaoAnterior")
                        .HasColumnType("int")
                        .HasColumnName("POSICAO_ANTERIOR");

                    b.Property<int>("PosicaoRanking")
                        .HasColumnType("int")
                        .HasColumnName("POSICAO_RANKING");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("SLUG");

                    b.Property<int>("TitulosTime")
                        .HasColumnType("int")
                        .HasColumnName("TITULOS_TIME");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED_AT");

                    b.Property<int>("Vitorias")
                        .HasColumnType("int")
                        .HasColumnName("VITORIAS");

                    b.HasKey("Id");

                    b.HasIndex("Pontos")
                        .HasDatabaseName("IX_TIME_PONTOS");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_TIME_SLUG_UNIQUE");

                    b.ToTable("T_TIMES", (string)null);
                });

            modelBuilder.Entity("FEMEE.Domain.Entities.Principal.Conquista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampeonatoId")
                        .HasColumnType("int")
                        .HasColumnName("CAMPEONATO_ID");

                    b.Property<DateTime>("DataConquista")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_CONQUISTA");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("IconeTitulo")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ICONE_TITULO");

                    b.Property<int>("Posicao")
                        .HasColumnType("int")
                        .HasColumnName("POSICAO");

                    b.Property<int>("TimeId")
                        .HasColumnType("int")
                        .HasColumnName("TIME_ID");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("TITULO");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.HasIndex("TimeId");

                    b.ToTable("T_CONQUISTAS", (string)null);
                });

            modelBuilder.Entity("FEMEE.Domain.Entities.Principal.Noticia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int")
                        .HasColumnName("AUTOR_ID");

                    b.Property<string>("Categoria")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("CATEGORIA");

                    b.Property<string>("Conteudo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CONTEUDO");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_PUBLICACAO");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("NOTICIA_URL");

                    b.Property<int>("NumeroComentarios")
                        .HasColumnType("int")
                        .HasColumnName("NUMERO_COMENTARIOS");

                    b.Property<DateTime>("Publicada")
                        .HasColumnType("datetime2")
                        .HasColumnName("PUBLICADA");

                    b.Property<string>("Resumo")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("RESUMO");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("SLUG");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("TITULO");

                    b.Property<int>("Vizualizacoes")
                        .HasColumnType("int")
                        .HasColumnName("VISUALIZACOES");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("DataPublicacao")
                        .HasDatabaseName("IX_NOTICIA_DATAPUBLICACAO");

                    b.HasIndex("Publicada")
                        .HasDatabaseName("IX_NOTICIA_PUBLICADA");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_NOTICIA_SLUG_UNIQUE");

                    b.ToTable("T_NOTICIAS", (string)null);
                });

            modelBuilder.Entity("FEMEE.Domain.Entities.Principal.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("USUARIO");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("SENHA");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TELEFONE");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int")
                        .HasColumnName("TIPO_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_USER_EMAIL_UNIQUE");

                    b.ToTable("T_USERS", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("FEMEE.Domain.Entities.Store.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Estoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("IX_PRODUTO_ATIVO");

                    b.HasIndex("Categoria")
                        .HasDatabaseName("IX_PRODUTO_CATEGORIA");

                    b.ToTable("T_PRODUTOS", (string)null);
                });

            modelBuilder.Entity("FEMEE.Domain.Entities.Principal.Jogador", b =>
                {
                    b.HasBaseType("FEMEE.Domain.Entities.Principal.User");

                    b.Property<DateTime>("DataEntradaTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_ENTRADA_TIME");

                    b.Property<DateTime>("DataSaidaTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_SAIDA_TIME");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("FOTO_URL");

                    b.Property<int>("Funcao")
                        .HasColumnType("int")
                        .HasColumnName("FUNCAO");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NICKNAME");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<int?>("TimeId")
                        .HasColumnType("int")
                        .HasColumnName("TIME_ID");

                    b.HasIndex("NickName")
                        .IsUnique()
                        .HasDatabaseName("IX_JOGADOR_NICKNAME_UNIQUE")
                        .HasFilter("[NICKNAME] IS NOT NULL");

                    b.HasIndex("TimeId", "Status")
                        .HasDatabaseName("IX_JOGADOR_TIMEID_STATUS");

                    b.ToTable("T_JOGADORES", (string)null);
                });

            modelBuilder.Entity("FEMEE.Domain.Entities.Campeonatos.Campeonato", b =>
                {
                    b.HasOne("FEMEE.Domain.Entities.Campeonatos.Jogo", "Jogo")
                        .WithMany("Campeonatos")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("FEMEE.Domain.Entities.Campeonatos.InscricaoCampeonato", b =>
                {
                    b.HasOne("FEMEE.Domain.Entities.Campeonatos.Campeonato", "Campeonato")
                        .WithMany("InscricoesCampeonatos")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_INSCRICAO_CAMPEONATO");

                    b.HasOne("FEMEE.Domain.Entities.Principal.User", "Capitao")
                        .WithMany("InscricoesCampeonatos")
                        .HasForeignKey("CapitaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_INSCRICAO_CAPITAO");

                    b.HasOne("FEMEE.Domain.Entities.Campeonatos.Time", "Time")
                        .WithMany("InscricoesCampeonatos")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_CONQUISTA_TIME");

                    b.Navigation("Campeonato");

                    b.Navigation("Capitao");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("FEMEE.Domain.Entities.Campeonatos.Partida", b =>
                {
                    b.HasOne("FEMEE.Domain.Entities.Campeonatos.Campeonato", "Campeonato")
                        .WithMany("Partidas")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PARTIDA_CAMPEONATO");

                    b.HasOne("FEMEE.Domain.Entities.Campeonatos.Time", "TimeA")
                        .WithMany("PartidasCasaTeam")
                        .HasForeignKey("TimeAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PARTIDA_TIMEA");

                    b.HasOne("FEMEE.Domain.Entities.Campeonatos.Time", "TimeB")
                        .WithMany("PartidasVisitanteTeam")
                        .HasForeignKey("TimeBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PARTIDA_TIMEB");

                    b.HasOne("FEMEE.Domain.Entities.Campeonatos.Time", "TimeVencedor")
                        .WithMany()
                        .HasForeignKey("TimeVencedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campeonato");

                    b.Navigation("TimeA");

                    b.Navigation("TimeB");

                    b.Navigation("TimeVencedor");
                });

            modelBuilder.Entity("FEMEE.Domain.Entities.Principal.Conquista", b =>
                {
                    b.HasOne("FEMEE.Domain.Entities.Campeonatos.Campeonato", "Campeonato")
                        .WithMany("Conquistas")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_CONQUISTA_CAMPEONATO");

                    b.HasOne("FEMEE.Domain.Entities.Campeonatos.Time", "Time")
                        .WithMany("Conquistas")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campeonato");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("FEMEE.Domain.Entities.Principal.Noticia", b =>
                {
                    b.HasOne("FEMEE.Domain.Entities.Principal.User", "Autor")
                        .WithMany("Noticias")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NOTICIA_USER");

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("FEMEE.Domain.Entities.Principal.Jogador", b =>
                {
                    b.HasOne("FEMEE.Domain.Entities.Principal.User", null)
                        .WithOne()
                        .HasForeignKey("FEMEE.Domain.Entities.Principal.Jogador", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FEMEE.Domain.Entities.Campeonatos.Time", "Time")
                        .WithMany("Jogadores")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_JOGADOR_TIME");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("FEMEE.Domain.Entities.Campeonatos.Campeonato", b =>
                {
                    b.Navigation("Conquistas");

                    b.Navigation("InscricoesCampeonatos");

                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("FEMEE.Domain.Entities.Campeonatos.Jogo", b =>
                {
                    b.Navigation("Campeonatos");
                });

            modelBuilder.Entity("FEMEE.Domain.Entities.Campeonatos.Time", b =>
                {
                    b.Navigation("Conquistas");

                    b.Navigation("InscricoesCampeonatos");

                    b.Navigation("Jogadores");

                    b.Navigation("PartidasCasaTeam");

                    b.Navigation("PartidasVisitanteTeam");
                });

            modelBuilder.Entity("FEMEE.Domain.Entities.Principal.User", b =>
                {
                    b.Navigation("InscricoesCampeonatos");

                    b.Navigation("Noticias");
                });
#pragma warning restore 612, 618
        }
    }
}
